# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name : 'Default'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Azure subscription 1'
    KeyVaultName: 'SecretHolder3'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: CmdLine@1
  displayName: Write Secret into file
  inputs:
    script: |
      echo $(DatabaseConnectionString)
      echo $(DatabaseConnectionString) > secret.txt
      cat secret.txt

- task: CopyFiles@1
  displayName: Copy Secrets File
  inputs:
    contents: secret.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Secrets File
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
    


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
